import {
  siCplusplus,
  siDiscord,
  siDotnet,
  siFirebase,
  siFlask,
  siGit,
  siGithub,
  siGodotengine,
  siHtml5,
  siJavascript,
  siNextdotjs,
  siPandas,
  siPostgresql,
  siPython,
  siPytorch,
  siReact,
  siSass,
  siScikitlearn,
  siTailwindcss,
  siTypescript,
  siVercel,
} from 'simple-icons';

// Named imports keep the bundle to the icons actually used. Add new ones here.
export const brandIcons = {
  siCplusplus,
  siDiscord,
  siDotnet,
  siFirebase,
  siFlask,
  siGit,
  siGithub,
  siGodotengine,
  siHtml5,
  siJavascript,
  siNextdotjs,
  siPandas,
  siPostgresql,
  siPython,
  siPytorch,
  siReact,
  siSass,
  siScikitlearn,
  siTailwindcss,
  siTypescript,
  siVercel,
};

export type BrandIconName = keyof typeof brandIcons;
